
# Deploy your app with
#
#    gcloud app deploy --project yourappid
#
# where "yourappid" is the actual id of your personal MyLife installation.

runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:

- url: /css
  static_dir: css
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
  secure: always

- url: .*
  script: main.app
  login: admin
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest  

inbound_services:
- mail
